engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: false
languages:
  JavaScript: true
  Ruby: true
ratings:
  paths:
  - app/**
exclude_paths:
- .codeclimate.yml
- app/assets/stylesheets/application.css.scss
- backup/**/*
