engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    config:
      languages:
      - ruby
      - javascript
    enabled: true
    exclude_fingerprints:
      - 689b9b135b5a4fc51a53565d81f703ef
      - 806a7cb23dee2ea8ab3e64a74d14c9b3
      - 143da1b4c6b5698287b6635a04396a0f
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: false
languages:
  JavaScript: true
  Ruby: true
ratings:
  paths:
  - app/**
exclude_paths:
- .codeclimate.yml
- app/assets/stylesheets/application.css.scss
- backup/**/*
- db/**/*
