engines:
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: false
languages:
  JavaScript: true
  Ruby: true
ratings:
  paths:
  - app/**
exclude_paths:
- .codeclimate.yml
- app/assets/stylesheets/application.css.scss
