AllCops:
  Exclude:
    - '**/Rakefile'
    - 'backup/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
