language: ruby
rvm:
  - "2.2.3"
before_script:
  - "mysql -e 'create database K2_test;'"
  - "cp ./.travis.database.yml ./config/database.yml"
notifications:
  email:
    recipients:
      - vshlyaga@acm.org
    on_success: change
    on_failure: always
